# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")


        self.ACU_A1_Tab = QtWidgets.QWidget()
        self.ACU_A1_Tab.setObjectName("ACU_A1_Tab")
        self.gridLayout = QtWidgets.QGridLayout(self.ACU_A1_Tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.ACU_A1_Tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.DrverSafetyBeltAlarmStatespinBox = QtWidgets.QSpinBox(self.ACU_A1_Tab)
        self.DrverSafetyBeltAlarmStatespinBox.setObjectName("DrverSafetyBeltAlarmStatespinBox")
        self.horizontalLayout_2.addWidget(self.DrverSafetyBeltAlarmStatespinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.ACU_A1_Tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spinBox = QtWidgets.QSpinBox(self.ACU_A1_Tab)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)


        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.ACU_A1_Tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.AirBagSysAlrmLampStsspinBox = QtWidgets.QSpinBox(self.ACU_A1_Tab)
        self.AirBagSysAlrmLampStsspinBox.setObjectName("AirBagSysAlrmLampStsspinBox")
        self.horizontalLayout_4.addWidget(self.AirBagSysAlrmLampStsspinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)


        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ACU_A1_Tab, "")



        self.ACU_A2_Tab = QtWidgets.QWidget()
        self.ACU_A2_Tab.setObjectName("ACU_A2_Tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ACU_A2_Tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.ACU_A2_Tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.LateralSensorStatespinBox = QtWidgets.QSpinBox(self.ACU_A2_Tab)
        self.LateralSensorStatespinBox.setObjectName("LateralSensorStatespinBox")
        self.horizontalLayout_5.addWidget(self.LateralSensorStatespinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ACU_A2_Tab, "")



        self.ACU_A3_Tab = QtWidgets.QWidget()
        self.ACU_A3_Tab.setObjectName("ACU_A3_Tab")
        self.tabWidget.addTab(self.ACU_A3_Tab, "")



        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.Timelabel = QtWidgets.QLabel(self.centralwidget)
        self.Timelabel.setObjectName("Timelabel")
        self.horizontalLayout.addWidget(self.Timelabel)
        self.Startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Startbutton.setObjectName("Startbutton")
        self.horizontalLayout.addWidget(self.Startbutton)
        self.PauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout.addWidget(self.PauseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DrverSafetyBeltAlarmState"))
        self.label_2.setText(_translate("MainWindow", "CrashDetected"))
        self.label_3.setText(_translate("MainWindow", "AirBagSysAlrmLampSts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ACU_A1_Tab), _translate("MainWindow", "ACU_A1"))
        self.label_4.setText(_translate("MainWindow", "LateralSensorState"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ACU_A2_Tab), _translate("MainWindow", "ACU_A2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ACU_A3_Tab), _translate("MainWindow", "ACU_A3"))
        self.Timelabel.setText(_translate("MainWindow", "00:000"))
        self.Startbutton.setText(_translate("MainWindow", "Start"))
        self.PauseButton.setText(_translate("MainWindow", "Pause"))
